### ISSUE TITLE
Required static files

### ISSUE THREAD

**Issue by hspuppy** [kate-v-stepanova/diricore#2]
Hey Stepanova,  awesome work on diricore. Would you help clarify the way to obtain/prepare the following static data files required by rpf_density and subseq scripts respectively. New to this area, thanks a lot.

```bash
# required by rpf density analysis
INDEXDATA_FILE="$BASE_DIR/static/${species}/transcript_data.hdf5";
MAPS_FILE="$BASE_DIR/static/${species}/codon_regions.width_61.hdf5";
MAPSSTART_FILE="$BASE_DIR/static/${species}/codon_regions.START_Other_ATG.width_61.hdf5";

# required by subseq analysis
INDEXDATAFN="$BASE_DIR/static/${species}/subseq_index_data.pkl.gz";
```

**Comment by dev1113** [comment]
Hey @hspuppy , We're facing the same issue. Could you tell how you solved this please?

Thank you so much!
